### ISSUE TITLE
Некорректное отображение ошибки

### ISSUE THREAD

**Issue by IgorIvanov123** [ResidentUstas/KeyBoardStyle#2]
При вводе пробела в строку ID при регистрации нового пользователя, сообщение об ошибке выводится в строку с ID, ожидается появление messagebox'а.
![image](https://user-images.githubusercontent.com/58205683/69983236-41dbb300-1547-11ea-87cf-d0344b968a8b.png)

**Comment by ResidentUstas** [comment]
Сообщение об ошибке вынесено в MessageBox
